<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Maitreya Developers</title>
</head>

<body>
    <?php include_once('include/header.php') ?>

    <div class="blog-post-sec">
        <div class="container">
            <div class="blog-area-part">
                <div class="title">
                    <h1>Team Working Blog</h1>
                </div>
                <div class="img-sec">
                    <img src="img/blogs/3.jpg" alt="blog-img">
                </div>
                <p>Posted on <span>06 September 2021</span></p>
                <p>Originally Answered: What is the best topic for a first time blog post? I've been blogging for 20
                    years now and many people have asked me this question in real life. Your very first post (the debut
                    post) in fact should be the corny <a href="">"Hello World!"</a> post that's often automatically
                    generated by your
                    blog provider or blog software. This serves as a marker of when your blog was born. This is usually
                    the post that historians (and search engines) decide the date of birth of the blog.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae incidunt nihil nam harum
                    recusandae illo enim quas. A eius aperiam distinctio harum explicabo consectetur dolore culpa illo,
                    aliquid impedit asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora labore
                    totam itaque, eveniet quae, repudiandae amet doloribus architecto aut tenetur quidem hic accusamus
                    officiis quam facere sint dolorem voluptate! Vero.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae incidunt nihil nam harum
                    recusandae illo enim quas. <a href="">A eius aperiam </a>distinctio harum explicabo consectetur
                    dolore culpa illo,
                    aliquid impedit asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora labore
                    totam itaque, eveniet quae, repudiandae amet doloribus architecto aut tenetur quidem hic accusamus
                    officiis quam facere sint dolorem voluptate! Vero.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae incidunt nihil nam harum
                    recusandae illo enim quas. A eius aperiam distinctio harum explicabo consectetur dolore culpa illo,
                    aliquid impedit asperiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora labore
                    totam itaque, eveniet quae, repudiandae amet doloribus architecto aut tenetur quidem hic accusamus
                    officiis quam facere sint dolorem voluptate! Vero.</p>
            </div>
        </div>
    </div>




    <!-- Blogs Section -->
    <section class="blog-section" id="blog">
        <div class="container">
            <div class="container title">
                <h1>Other Blogs</h1>
            </div>
            <div class="blog-area">
                <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4" data-aos="fade-up">
                        <div class="blog-content">
                            <div class="box">
                                <div class="img">
                                    <img src="img/blogs/1.jpg" alt="blog">
                                </div>
                                <div class="info">
                                    <span>01 Sept 2021</span> <span>Coading</span>
                                    <h5>Coading Blog</h5>
                                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit porro odit rem.</p>
                                    <a class="btn" href="blogs-coding-blog.php">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="col-md-6 col-lg-4" data-aos="fade-up">
                        <div class="blog-content">
                            <div class="box">
                                <div class="img">
                                    <img src="img/blogs/2.jpg" alt="blog">
                                </div>
                                <div class="info">
                                    <span>04 Sept 2021</span> <span>Coading</span>
                                    <h5>Wed Design Blog</h5>
                                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit porro odit rem.</p>
                                    <a class="btn" href="blogs-website-design-blog.php">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php include_once('include/footer.php') ?>


</body>

</html>